export const metadata = { title: 'About Day Lab' };

const mono = "'SF Mono','Monaco','Inconsolata',monospace";
const serif = "'Playfair Display','Georgia',serif";

const S = {
  bg: '#0A0A0A',
  surface: '#141210',
  border: '#2a2520',
  text: '#f0ece4',
  muted: '#9A9088',
  dim: '#6A6258',
  accent: '#D08828',
  green: '#6abf7b',
};

function Section({ title, children }) {
  return (
    <section style={{ marginBottom: 52 }}>
      <h2 style={{ fontFamily: mono, fontSize: 10, letterSpacing: '0.12em', textTransform: 'uppercase', color: S.accent, margin: '0 0 16px' }}>
        {title}
      </h2>
      <div style={{ fontFamily: mono, fontSize: 12, color: S.muted, lineHeight: 1.85, letterSpacing: '0.01em' }}>
        {children}
      </div>
    </section>
  );
}

function ScoreRow({ name, desc }) {
  return (
    <div style={{ display: 'flex', gap: 16, padding: '11px 0', borderBottom: `1px solid ${S.border}` }}>
      <span style={{ fontFamily: mono, fontSize: 11, color: S.text, flexShrink: 0, width: 110, letterSpacing: '0.02em' }}>{name}</span>
      <span style={{ fontFamily: mono, fontSize: 11, color: S.muted, lineHeight: 1.7 }}>{desc}</span>
    </div>
  );
}

export default function AboutPage() {
  return (
    <div style={{ background: S.bg, minHeight: '100vh', color: S.text }}>
      <div style={{ maxWidth: 640, margin: '0 auto', padding: '64px 24px 80px' }}>

        {/* Header */}
        <div style={{ marginBottom: 56 }}>
          <a href="/" style={{ fontFamily: mono, fontSize: 10, letterSpacing: '0.1em', color: S.dim, textDecoration: 'none', textTransform: 'uppercase', display: 'block', marginBottom: 40 }}>← Day Lab</a>
          <h1 style={{ fontFamily: serif, fontSize: 42, fontWeight: 400, letterSpacing: '-0.02em', margin: '0 0 16px', color: S.text }}>About Day Lab</h1>
          <p style={{ fontFamily: mono, fontSize: 12, color: S.muted, lineHeight: 1.8, margin: 0 }}>
            Day Lab is a personal health OS — a single place to log meals, tasks, notes, and workouts, with AI that surfaces patterns across your data over time.
          </p>
        </div>

        <Section title="What it does">
          <p style={{ margin: '0 0 14px' }}>Day Lab pulls data from Oura, Strava, and Apple Health and combines it with what you log manually — meals, tasks, notes, journal entries — into a unified daily view.</p>
          <p style={{ margin: '0 0 14px' }}>The AI Insights feature reads your actual data and generates a short analysis each day: what your sleep and recovery look like, how your activity compares to recent weeks, and whether patterns in your nutrition or schedule are worth paying attention to.</p>
          <p style={{ margin: 0 }}>The voice entry bar lets you log anything in natural language. "Had eggs and coffee for breakfast, 30 min run, feeling good" — Day Lab parses and stores it.</p>
        </Section>

        <Section title="How scores are calculated">
          <p style={{ margin: '0 0 20px' }}>Each day gets up to four scores, each 0–100. Scores only appear when there's real data to calculate from — you'll never see a fabricated number.</p>

          <div style={{ border: `1px solid ${S.border}`, borderRadius: 8, overflow: 'hidden', marginBottom: 20 }}>
            <ScoreRow name="Sleep" desc="Combines Oura sleep score (if connected) with Apple Health sleep duration. Oura's score is the primary signal when available; duration alone provides a baseline otherwise." />
            <ScoreRow name="Activity" desc="Uses steps, active minutes, and workout data from Apple Health or Strava. Weighted toward intensity and consistency over raw step count. Null if no activity data exists for the day." />
            <ScoreRow name="Recovery" desc="Based on Oura readiness score and HRV. Reflects how prepared your body is for exertion. Requires Oura for meaningful scores." />
            <ScoreRow name="Resilience" desc="A composite of sleep, activity, and recovery — weighted toward whichever signals are available. Represents overall adaptive capacity for the day." />
          </div>

          <p style={{ margin: 0, color: S.dim, fontSize: 11 }}>
            Historical scores are backfilled when you first connect a data source, and recalculated whenever you reconnect. You can always trigger a recalculation by disconnecting and reconnecting a source.
          </p>
        </Section>

        <Section title="Data & privacy">
          <p style={{ margin: '0 0 14px' }}>Your data is stored in a private Supabase database tied to your account. Day Lab does not sell your data or share it with third parties.</p>
          <p style={{ margin: '0 0 14px' }}>AI insights are generated by sending your health metrics to the Anthropic Claude API. This data is not used to train AI models under Anthropic's API terms.</p>
          <p style={{ margin: 0 }}>Oura tokens are stored encrypted in your settings row. Apple Health data is synced on-device via the iOS app and sent to your account over HTTPS.</p>
        </Section>

        {/* Legal links */}
        <div style={{ borderTop: `1px solid ${S.border}`, paddingTop: 28, display: 'flex', gap: 24 }}>
          <a href="/terms" style={{ fontFamily: mono, fontSize: 10, letterSpacing: '0.08em', textTransform: 'uppercase', color: S.dim, textDecoration: 'none' }}>Terms of Service</a>
          <a href="/privacy" style={{ fontFamily: mono, fontSize: 10, letterSpacing: '0.08em', textTransform: 'uppercase', color: S.dim, textDecoration: 'none' }}>Privacy Policy</a>
          <a href="mailto:hello@daylab.me" style={{ fontFamily: mono, fontSize: 10, letterSpacing: '0.08em', textTransform: 'uppercase', color: S.dim, textDecoration: 'none' }}>Contact</a>
        </div>

      </div>
    </div>
  );
}
