name: DayLab
options:
  bundleIdPrefix: me.daylab
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15"
  createIntermediateGroups: true

targets:
  DayLab:
    type: application
    platform: iOS
    sources:
      - Sources/DayLab
    resources:
      - Assets.xcassets
    settings:
      base:
        PRODUCT_NAME: "Day Lab"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        ENABLE_BITCODE: NO
        TARGETED_DEVICE_FAMILY: "1,2"
        PRODUCT_BUNDLE_IDENTIFIER: me.daylab.app
        DEVELOPMENT_TEAM: AZ65YJVYKM
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE_OUTPUT_FORMAT: binary
        INFOPLIST_KEY_CFBundleDisplayName: "Day Lab"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleLightContent
        INFOPLIST_KEY_UIViewControllerBasedStatusBarAppearance: NO
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
        INFOPLIST_OTHER: "$(SRCROOT)/Sources/DayLab/Info-additions.plist"
